SELECT * FROM Cars..cardata;

SELECT * FROM Cars..cardata ORDER BY Kms_Driven DESC;
-- Activa 3g	2008	0.17	0.52	500000	Petrol	Individual	Automatic	0 ( CAR WHICH DROVE MAX KMS)

SELECT CAR_NAME, SUM(Selling_Price) AS 'TOTAL SELLING PRICE OF CAR' FROM Cars..cardata GROUP BY CAR_NAME ORDER BY 'TOTAL SELLING PRICE OF CAR' DESC;

-- Fortuner is the car which has max total selling price

SELECT CAR_NAME, YEAR, MAX(SELLING_PRICE) AS MSP FROM Cars..cardata GROUP BY CAR_NAME, YEAR ORDER BY YEAR ASC, MSP DESC;

-- Here car sx4 is having max selling price in 2003, and only 2 cars were sold in 2003, similarly for other years.

SELECT FUEL_TYPE, COUNT(CAR_NAME) NUMBER_OF_CARS FROM Cars..cardata GROUP BY Fuel_Type;

-- ONLY 2 CARS RAN ON CNG, 60 ON DIESEL, 239 ON PETROL

WITH CHECK_DUPLICATE AS (
SELECT *, ROW_NUMBER() OVER(PARTITION BY CAR_NAME, YEAR, SELLING_PRICE, PRESENT_PRICE, KMS_DRIVEN, FUEL_TYPE, SELLER_TYPE, TRANSMISSION, OWNER ORDER BY CAR_NAME) AS RNK FROM Cars..cardata)

SELECT * FROM CHECK_DUPLICATE WHERE RNK>1;

---There are two entries which are duplicated

SELECT *, (Present_Price - Selling_Price) as DIFFERENCE_IN_VALUATION FROM Cars..cardata;

-- ALL PRICES ARE INCREASED AS WE CAN SEE

SELECT CAR_NAME, Kms_Driven FROM Cars..cardata WHERE Kms_Driven = (SELECT MAX(KMS_DRIVEN) FROM Cars..cardata);

-- SAME AS WE SAW EARLIER 
-- SELECT * FROM Cars..cardata ORDER BY Kms_Driven DESC;
-- Activa 3g	2008	0.17	0.52	500000	Petrol	Individual	Automatic	0 ( CAR WHICH DROVE MAX KMS)

--SELECT CAR_NAME, MAX(Kms_Driven) FROM Cars..cardata WHERE Kms_Driven IN (SELECT KMS_DRIVEN  FROM Cars..cardata MINUS SELECT MAX(KMS_DRIVEN) FROM Cars..cardata);

SELECT CAR_NAME, KMS_DRIVEN FROM Cars..cardata WHERE Kms_Driven = (
SELECT MAX(KMS_DRIVEN) FROM Cars..cardata WHERE Kms_Driven != (SELECT MAX(KMS_DRIVEN) FROM Cars..cardata));

-- CAR HAVING 2ND MAX NUMBER OF KMS DRIVEN
-- USING DENSE_RANK
WITH CTE AS (
SELECT *, DENSE_RANK() OVER(ORDER BY KMS_DRIVEN DESC) AS RANKED_KMS FROM Cars..cardata)
SELECT * FROM CTE WHERE CTE.RANKED_KMS = 2;

---CASE WHEN 

SELECT *, CASE WHEN TRANSMISSION = 'MANUAL' THEN 1
			WHEN TRANSMISSION = 'AUTOMATIC' THEN 2
			ELSE TRANSMISSION
			END AS TRANSMISSION_IN_NUM
FROM Cars..cardata

SELECT YEAR, COUNT(*) AS NUMBER_OF_CARS_SOLD FROM Cars..cardata GROUP BY YEAR ORDER BY NUMBER_OF_CARS_SOLD DESC

-- 2015 WAS THE YEAR HAVING MOST NUMBER OF CARS SOLD

SELECT YEAR, SUM(SELLING_PRICE) TOTAL_YEARLY_REVENUE FROM cardata GROUP BY YEAR ORDER BY TOTAL_YEARLY_REVENUE DESC;

-- AS EXPECTED, 2015 WAS THE YEAR WHICH BROUGHT MOST REVENUE FROM SALES

SELECT * FROM cardata;

SELECT *, 2023 - YEAR AS GAP FROM cardata;

-- LIKE

SELECT CAR_NAME, FUEL_TYPE FROM cardata WHERE Car_Name LIKE '%ciaz%';

-- So ciaz can run or either Petrol or Diesel.

SELECT car_name, count(CAR_NAME), FUEL_TYPE FROM cardata WHERE Car_Name LIKE '%ciaz%' group by Fuel_Type, car_name;

-- Ciaz has 4 number of cars running on Diesel while 5 running on Petrol

-- That's it for now.